---
language: python
services: docker

env:
  global:
    - ROLE_NAME: certbot
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
      MOLECULE_PLAYBOOK: playbook-source-install.yml
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_PLAYBOOK: playbook-source-install.yml
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME vdzhorov.$ROLE_NAME
  - cd vdzhorov.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
