---
- name: Set wkhtmltopdf_download_url var
  set_fact:
    wkhtmltopdf_download_url: "{{ wkhtmltopdf_base_download_url }}/{{ wkhtmltopdf_version }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_amd64.deb"

- name: Download wkhtmltopdf package.
  get_url:
    url: "{{ wkhtmltopdf_download_url }}"
    dest: "{{ wkhtmltopdf_download_dest }}"

- name: Install wkhtmltopdf (Debian 9).
  apt:
    deb: "{{ wkhtmltopdf_download_dest }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_amd64.deb"
    state: present
  when: ansible_distribution_release == "stretch"

- name: Install wkhtmltopdf (Debian 10).
  apt:
    deb: "{{ wkhtmltopdf_download_dest }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_amd64.deb"
    state: present
  when: ansible_distribution_release == "buster"

- name: Install wkhtmltopdf (Ubuntu 16.04).
  apt:
    deb: "{{ wkhtmltopdf_download_dest }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_amd64.deb"
    state: present
  when: ansible_distribution_release == "xenial"

- name: Install wkhtmltopdf (Ubuntu 18.04).
  apt:
    deb: "{{ wkhtmltopdf_download_dest }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_amd64.deb"
    state: present
  when: ansible_distribution_release == "bionic"

- name: Install wkhtmltopdf (Ubuntu 20.04).
  apt:
    deb: "{{ wkhtmltopdf_download_dest }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_amd64.deb"
    state: present
  when: ansible_distribution_release == "focal"
...
