---
- name: Install wkhtmltopdf (Debian).
  apt:
    deb: "{{ wkhtmltopdf_download_dest }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_amd64.deb"
    state: present
  when: >
    ansible_distribution_release == "stretch" or
    ansible_distribution_release == "buster" or
    ansible_distribution_release == "xenial" or
    ansible_distribution_release == "bionic" or
    ansible_distribution_release == "focal"
...
