---
- set_fact:
    wkhtmltopdf_download_url: "https://github.com/wkhtmltopdf/packaging/releases/download/{{ wkhtmltopdf_version }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_arm64.deb"

- name: Download wkhtmltopdf package.
  get_url:
    url: "{{ wkhtmltopdf_download_url }}"
    dest: "{{ wkhtmltopdf_download_dest }}"

- name: Install wkhtmltopdf (Debian 9).
  apt:
    deb: "{{ wkhtmltopdf_download_dest }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_arm64.deb"
    state: present
  when: ansible_distribution_release == "stretch"

- name: Install wkhtmltopdf (Debian 10).
  apt:
    deb: "{{ wkhtmltopdf_download_dest }}/wkhtmltox_{{ wkhtmltopdf_version }}.{{ ansible_distribution_release }}_arm64.deb"
    state: present
  when: ansible_distribution_release == "buster"
...
