---
- name: Install wkhtmltopdf (CentOS).
  yum:
    name: "{{ wkhtmltopdf_download_dest }}/wkhtmltox-{{ wkhtmltopdf_version }}.centos{{ ansible_distribution_major_version }}.x86_64.rpm"
    state: present
  when: >
    (ansible_distribution == "CentOS") and
    (ansible_distribution_major_version == "7" or
    ansible_distribution_major_version == "8")
...
